Bookstore/Pages/Pay.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Bookstore.Infrastructure;
using Bookstore.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Bookstore.Pages
{
    public class PayModel : PageModel
    {
        private BooksRepository repository;

        //constructor
        public PayModel (BooksRepository repo, Cart cartservice)
        {
            repository = repo;
            Cart = cartservice;
        }
        //properties
        public Cart Cart { get; set; }
        public string ReturnUrl { get; set; }
        //methods
        public void OnGet(string returnUrl)
        {
            ReturnUrl = returnUrl ?? "/";
        }

        public IActionResult OnPost(long BookID, string returnUrl)
        {
            Books books = repository.Books.FirstOrDefault(p => p.BookID == BookID);
            Cart = HttpContext.Session.GetJson<Cart>("cart") ?? new Cart();
            Cart.AddItem(books, 1);
            return RedirectToPage(new { returnUrl = returnUrl });
        }

        public IActionResult OnPostRemove(long productId, string returnUrl)
        {
            Cart.RemoveLine(Cart.Lines.First(cl =>
                cl.Books.BookID == BookID).Books);
            return RedirectToPage(new { returnUrl = returnUrl });
        }
    }
}

Bookstore/Pages/Pay.cshtml
@page

@model Bookstore.Pages.PayModel

@{
}

<h2>Your Cart</h2>

<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Book</th>
            <th>Quantity</th>
            <th class="text-right">Price</th>
            <th class="text-right">Subtotal</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var line in Model.Cart.Lines)
        {
            <tr>
                <td class="text-left">@line.Books.Title</td>
                <td class="text-center">@line.Quantity</td>
                <td class="text-right">@line.Books.Price.ToString("c")</td>
                <td class="text-right">@((line.Quantity * line.Books.Price).ToString("c"))</td>
                <td class="text-center">
                    <form asp-page-handler="Remove" method="post">
                        <input type="hidden" name="BookID"
                               value="@line.Books.BookID" />
                        <input type="hidden" name="returnUrl"
                               value="@Model.ReturnUrl" />
                        <button type="submit" class="btn btn-sm btn-danger">
                            Remove
                        </button>
                    </form>
                </td>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3" class="text-right">Total:</td>
            <td class="text-right">@Model.Cart.ComputeTotalSum().ToString("c")</td>
        </tr>
    </tfoot>
</table>

<div class="text-center">
    <a class="btn btn-primary" href="@Model.ReturnUrl">Continue Shopping</a>
</div>